# replace japanese prounounces   Update : 2025/08/27 09:30JST
#                                Update : 2025/08/29 08:30JST
#                                Update : 2025/08/30 17:35JST
#                                Update : 2025/09/05 08:33JST
#                                Update : 2025/09/26 07:50JST

# replace_rules.py
replace_rules = [

    { "target": "&", "corrected": ""},

    { "target": " 日", "corrected": "日"},
    { "target": " 時", "corrected": "時"},
    { "target": " 分", "corrected": "分"},
    { "target": " 回", "corrected": "回"},
    { "target": " 秒", "corrected": "秒"},
    { "target": " 個", "corrected": "個"},

    { "target": " %", "corrected": "%"},
    { "target": "■", "corrected": "。"},
    { "target": " -> ", "corrected": " 矢印 "},
    { "target": " >= ", "corrected": " 大なりイコール "},
    { "target": " <= ", "corrected": " 小なりイコール "},
    { "target": " > = ", "corrected": " 大なりイコール "},
    { "target": " < = ", "corrected": " 小なりイコール "},
    { "target": ">= ", "corrected": " 大なりイコール "},
    { "target": "<= ", "corrected": " 小なりイコール "},
    
    { "target": "accessKeyId ", "corrected": "access Key Id"},
    { "target": "ACM ", "corrected": "エーシーエム"},
    { "target": "(ACM)", "corrected": "エーシーエム"},
    { "target": "AdminPolicy", "corrected": "アドミンポリシー"},
    { "target": "AES-256", "corrected": " A E S 256"},
    { "target": "Aggregate", "corrected": "アグリゲート"},
    { "target": "ALB", "corrected": "エーエルビー"},
    { "target": "amazon", "corrected": " amazon "},
    { "target": "After", "corrected": "After "},
    { "target": "Allowed", "corrected": " Allowed "},
    { "target": " Allow ", "corrected": " アロウ "},
    { "target": "Allow", "corrected":  "アロウ" },
    { "target": "Amazon MWAA", "corrected": " Amazon M W A A "},
    { "target": "AMI", "corrected": "エーエムアイ"},
    { "target": "Application", "corrected": " Application "},
    { "target": "appspec", "corrected": " app spec "},
    { "target": "AppSpec", "corrected": " App Spec "},
    { "target": "AppStream", "corrected": "アップストリーム"},
    { "target": "Artifact", "corrected": "アーティファクト"},
    { "target": "AssumeRole", "corrected": " Assume Role "},
    { "target": "Attributes", "corrected": " アトリビューツ "},
    { "target": "AuroraReplicaLagMaximum", "corrected": "オーロラレプリカラグマキシマム"},
    { "target": "Authorization", "corrected": " Authorization "},
    { "target": "AutoML", "corrected": " Auto M L "},    
    { "target": "AWS SES", "corrected": "AWS S E S "},
    { "target": "bucket", "corrected": "バケット"},
    { "target": "buildspec", "corrected": "buildspec "},
    { "target": "Batch", "corrected": " Batch "},
    { "target": "Before", "corrected": " Before "},
    { "target": "Bucket", "corrected": "バケット"},
    { "target": "CacheCluster", "corrected": "キャッシュクラスター"},
    { "target": "CDCLatencyTarget", "corrected": " C D Latency Target "},    
    { "target": "CentOS", "corrected": "セントオーエス"},
    { "target": "Client", "corrected": " Client "},
    { "target": "cloud", "corrected": " cloud "},
    { "target": "CloudFront", "corrected": "クラウドフロント"},
    { "target": "CloudWatchAgent", "corrected": "クラウドウオッチエージェント"},
    { "target": "CloudWatch", "corrected": "クラウドウオッチ"},
    { "target": "CloudFormation", "corrected": "クラウドフォーメーション"},
    { "target": "CloudHSM", "corrected": "クラウドエイチエスエム"},
    { "target": "CNAME", "corrected": "シーネーム"},
    { "target": "CodeBuild", "corrected": "コードビルド"},
    { "target": "CODEBUILD_SRC_DIR", "corrected": "コードビルド エスアールシー　ディーアイアール "},
    { "target": "codebuild", "corrected": "code build "},
    { "target": "codecommit ", "corrected": "code commit "},
    { "target": "CodeCommit", "corrected": "コードコミット"},
    { "target": "CodeDeploy", "corrected": "コードデプロイ"},
    { "target": "CodePipeline", "corrected": "コードパイプライン"},
    { "target": "Cognito", "corrected": "コグニート"},
    { "target": "Conditions", "corrected": " コンディションズ "},
    { "target": "Condition", "corrected": " Condition "},
    { "target": "Connection", "corrected": " Connection "},
    { "target": "Configuration", "corrected": " Configuration "},
    { "target": "CoolDown", "corrected": "Cool Down"},
    { "target": "CORS ", "corrected": "C O R S "},
    { "target": "(CORS)", "corrected": " C O R S "},
    { "target": "CORSRule", "corrected": "C O R S Rule "},
    { "target": "Count", "corrected": " Count "},
    { "target": "CPUCreditBalance", "corrected": "シーピーユークレジットバランス"},
    { "target": "CPUUtilization", "corrected": "シーピーユーユーティリゼーション"},
    { "target": "CreationPolicy", "corrected": "クリエイションポリシー"},
    { "target": "DataKey", "corrected": " Data Key "},
    { "target": "Database", "corrected": " データベース "},
    { "target": "DataBrew", "corrected": " データブリュー "},
    { "target": "DataFrame", "corrected": " データフレーム "},
    { "target": "Dataset", "corrected": " データセット "},
    { "target": "DataSync", "corrected": " データシンク "},   
    { "target": "DataZone", "corrected": " データゾーン "},   
    { "target": "datetime", "corrected": " date time "},
    { "target": "DDoS", "corrected": " D DoS "},
    { "target": "Decrypt", "corrected": " デクリプト "},
    { "target": "Default", "corrected": " Default "},
    { "target": "Delay", "corrected": " Delay "},
    { "target": "DeleteAPI", "corrected": "デリートエーピーアイ"},
    { "target": "DeleteItem", "corrected": " Delete Item "},
    { "target": "DeleteObject", "corrected": "デリートオブジェクト"},
    { "target": "DeletionPolicy", "corrected": "デリーションポリシー"},
    { "target": "DependentCondition", "corrected": " Dependent Condition "},
    { "target": "DependsOn", "corrected": " Depends On "},
    { "target": "DevOps", "corrected": "デブオプス"},
    { "target": "DPU", "corrected": " D P U "},    
    { "target": "DryRun", "corrected": "Dry Run "},
    { "target": "dryrun", "corrected": " dry run "},
    { "target": "DynamicFrame", "corrected": " ダイナミック フレーム "},    
    { "target": "DynamoDB", "corrected": "ダイナモデービー"},
    { "target": "EC2", "corrected": "イーシーツー"},
    { "target": "EC2", "corrected": "イーシーツー"},
    { "target": " ecr ", "corrected": " e c r "},
    { "target": " ECR）", "corrected": " E C R ）"},
    { "target": " ECR ", "corrected": " E C R "},
    { "target": "、ECR ", "corrected": "、 E C R )"},
    { "target": " EFS ", "corrected": " E F S "},
    { "target": "、EFS ", "corrected": "、E F S "},
    { "target": "。EFS ", "corrected": "。E F S "},
    { "target": "Amazon EFS", "corrected": "Amazon E F S "},
    { "target": "EIP ", "corrected": "E I P "},
    { "target": " EKS ", "corrected": " E K S "},
    { "target": "ElastCache", "corrected": "エラスティキャッシュ"},
    { "target": "EastiCache", "corrected": "エラスティキャッシュ"},
    { "target": "Elasticache", "corrected": "エラスティキャッシュ"},
    { "target": "ElastiCache", "corrected": "エラスティキャッシュ"},
    { "target": "ElasticCache", "corrected": "エラスティキャッシュ"},
    { "target": "Elasticsearch", "corrected": "エラスティックサーチ"},
    { "target": "elastic", "corrected": " elastic "},
    { "target": "ELB", "corrected": "イーエルビー"},
    { "target": "EnableTerminationProtection", "corrected": "イネーブルターミネーションプロテクション"},
    { "target": "Encoded", "corrected": "エンコーデッド"},
    { "target": "Encrypt", "corrected": "エンクリプト"},
    { "target": "Error", "corrected": " Error "},
    { "target": "Exceeded", "corrected": " エクシーデッド "},
    { "target": "Exception", "corrected": " Exception "},
    { "target": "failure", "corrected": "フェイラー"},
    { "target": "FIFO ", "corrected": "F I F O "},
    { "target": "FIFO（", "corrected": "F I F O（"},
    { "target": "fmeval", "corrected": " f m eval "},
    { "target": "Function", "corrected": " Function "},
    { "target": "GetItem", "corrected": " Get Item "},
    { "target": "GetObject", "corrected": " Get Object "},
    { "target": "getRecords", "corrected": "get Records"},
    { "target": "GetRecords", "corrected": "ゲットレコーズ"},
    { "target": "GetRole", "corrected": " Get Role "},
    { "target": "GitHub", "corrected": "ギットハブ"},
    { "target": "GitPull", "corrected": "Git Pull"},
    { "target": "GitPush", "corrected": "Git Push"},
    { "target": "git rebase", "corrected": " git リベース "},    
    { "target": "GroupDesiredCapacity", "corrected": "グループデザイアドキャパシティ"},
    { "target": "Group", "corrected": " Group "},
    { "target": "Instances", "corrected": " Instances "},
    { "target": " gp2 ", "corrected": "ジーピーツー"},
    { "target": "hi1.", "corrected": " h i 1 . "},
    { "target": " HA ", "corrected": "エイチエー"},
    { "target": "HoldCondition", "corrected": "ホールドコンディション"},
    { "target": "Hosts", "corrected": "ホスツ"},
    { "target": " iam ", "corrected": "アイアム"},
    { "target": "：iam ", "corrected": "：アイアム"},
    { "target": "iam:", "corrected": "アイアム"},
    { "target": "IAM", "corrected": "アイアム"},
    { "target": "ICMP", "corrected": " I C M P "},
    { "target": "(IdP)", "corrected": " I D P "},
    { "target": " IGW ", "corrected": " I G W "},
    { "target": "InstanceBootTime", "corrected": "Instance Boot Time"},
    { "target": "instances", "corrected": " インスタンシーズ "},
    { "target": "iptables", "corrected": "アイピーテーブルズ"},
    { "target": "(io1)", "corrected": " ( I O 1) "},
    { "target": "IOPS ", "corrected": " I O P S "},
    { "target": "IPAM ", "corrected": " I P A M "},
    { "target": "IPSec ", "corrected": "アイピーセック"},
    { "target": "JSON", "corrected": "ジェイソン"},
    { "target": "Kinesis", "corrected": "キネシス"},
    { "target": " LDAP", "corrected": "エルダップ"},
    { "target": "LegalHold", "corrected": "リーガルホールド"},
    { "target": "LIFO ", "corrected": "L I F O "},
    { "target": "LIFO（", "corrected": "L I F O（"},
    { "target": "LightGBM", "corrected": " Light G B M "},
    { "target": "Lightsail", "corrected": "ライトセイル"},
    { "target": "ListObjects", "corrected": " List Objects "},
    { "target": "list-roles", "corrected": "リストロールズ"},
    { "target": " m2.", "corrected": " m 2."},
    { "target": "MariaDB", "corrected": "Maria DB"},
    { "target": "Memcached", "corrected": "メムキャッシュド"},
    { "target": "Message", "corrected": " Message "},
    { "target": "MemoryUtilization", "corrected": "メモリーユーティリゼーション"},
    { "target": "MiB", "corrected": " メビバイト 毎"},
    { "target": "MongoDB", "corrected": " モンゴディービー "},    
    { "target": "MWAA", "corrected": " M W A A "},
    { "target": "MySQL", "corrected": "マイエスキューエル"},
    { "target": "Negotiation", "corrected": " Negotiation "},
    { "target": "NetApp", "corrected": " ネットアップ "},
    { "target": "NLB", "corrected": "エヌエルビー"},
    { "target": "NoEcho", "corrected": "No Echo"},
    { "target": "NoSQL", "corrected": "No SQL "},
    { "target": "OAI ", "corrected": " O A I "},
    { "target": "occurred", "corrected": "オカード"},
    { "target": "ODBC", "corrected": " O D B C "},    
    { "target": "(OIDC)", "corrected": "( O I D C )"},
    { "target": "OnFailure", "corrected": "オンフェイラー"},
    { "target": " ONTAP", "corrected": " オンタップ "},
    { "target": "Open", "corrected": " Open "},
    { "target": "Opsworks", "corrected": "オプスワークス"},
    { "target": "OpsWorks", "corrected": "オプスワークス"},
    { "target": " OU ", "corrected": " O U "},
    { "target": "package", "corrected": "パッケージ"},
    { "target": "PauseTime", "corrected": "Pause Time"},
    { "target": "PassRole", "corrected": " Pass Role "},
    { "target": "Period", "corrected": " Period "},
    { "target": "PartiQL", "corrected": " パーティクル "},    
    { "target": "PII", "corrected": " ピーアイアイ "},
    { "target": "PKI", "corrected": "ピーケーアイ"},
    { "target": "PostgreSQL", "corrected": "ポストグレ SQL"},
    { "target": "Policy", "corrected": " Policy "},
    { "target": "Private", "corrected": " Private "},
    { "target": "productID", "corrected": " produce ID "},
    { "target": "Provisioned", "corrected": " プロビジョンド "},
    { "target": "PutItem", "corrected": " Put Item "},
    { "target": "PutMetricData", "corrected": "プットメトリックデータ"},
    { "target": "PutObject", "corrected": "Put Object"},
    { "target": "PutObjectAcl", "corrected": "プットオブジェクトエーシーエル"},
    { "target": "PutRecords", "corrected": "プットレコーズ"},
    { "target": "PutTelemetryRecords", "corrected": "Put Telemetry Records"},
    { "target": "PutTraceSegments", "corrected": "Put Trace セグメンツ"},
    { "target": "QuickSight", "corrected": "クイックサイト"},
    { "target": "RAID ", "corrected": "レイド"},
    { "target": " RCU ", "corrected": " R C U "},
    { "target": "(RCU)", "corrected": "( R C U "},
    { "target": "REDIS", "corrected": "レディス"},
    { "target": "Redis", "corrected": "レディス"},
    { "target": "ReceiveMessage", "corrected": " Receive Message "},
    { "target": "Received ", "corrected": " レシーブド "},
    { "target": "RequestCountPerTarget", "corrected": "リクエストカウントパーターゲット"},
    { "target": "repositories", "corrected": " レポジトリーズ "},
    { "target": "Repositories", "corrected": " レポジトリーズ "},
    { "target": "Repository", "corrected": " Repository "},
    { "target": "Resolution", "corrected": " Resolution "},
    { "target": "Resource", "corrected": " Resource "},
    { "target": "RESTful API", "corrected": "レストフルエーピーアイ"},
    { "target": "Retention", "corrected": " Retention "},
    { "target": "reviewID", "corrected": " review ID "},
    { "target": "（RODC）", "corrected": " （R O D C） "},
    { "target": "ROLLBACK", "corrected": " ロールバック "},
    { "target": "Runtime", "corrected": " ランタイム "},
    { "target": " S3 ", "corrected": " エススリー "},
    { "target": "。S3 ", "corrected": "。 エススリー "},
    { "target": "s3:", "corrected": "。 エススリー :"},
    { "target": "Amazon S3", "corrected": " Amazon エススリー "},
    { "target": "ScheduledActions", "corrected": "Scheduled Actions"},
    { "target": "SAML ", "corrected": " サムル "},
    { "target": "Seconds", "corrected": " Seconds "},
    { "target": "secretKey", "corrected": "secret Key"},
    { "target": "Security", "corrected": " Security "},
    { "target": "serverless", "corrected": " サーバーレス "},     
    { "target": "Serverless", "corrected": " サーバーレス "},     
    { "target": "Service", "corrected": " Service "},
    { "target": "ServiceToken", "corrected": " Service Token "},     
    { "target": " SES ", "corrected": "エスイーエス"},
    { "target": "SSL", "corrected": " SSL "},
    { "target": "SSM", "corrected": " SSM "},
    { "target": "Start", "corrected": " Start "},
    { "target": "Storage", "corrected": " Storage "},
    { "target": "StringEquals", "corrected": "ストリングイコールス"},
    { "target": "SysOps", "corrected": "シスオプス"},
    { "target": "SystemsManager", "corrected": "Systems Manager"},
    { "target": "Throttling", "corrected": " Throttling "},
    { "target": "Throughput", "corrected": " Throughput "},
    { "target": "TraceGraph ", "corrected": " Trace Graph "},
    { "target": "Traces", "corrected": " Traces "},
    { "target": "Transcoder", "corrected": " トランスコーダー "},
    { "target": "Unauthorized", "corrected": "Unauthorized "},
    { "target": "undefined", "corrected": " undefined "},
    { "target": "UpdateItem", "corrected": " Update Item "},
    { "target": "UpdatePolicy", "corrected": "アップデートポリシー"},
    { "target": "UploadArchive ", "corrected": " Upload Archive "},
    { "target": "us-east-", "corrected": "ユーエスイースト "},
    { "target": "us-west-", "corrected": "ユーエスウエスト "},
    { "target": "UserData", "corrected": " User Data "},
    { "target": "UTC", "corrected": " U T C "},
    { "target": "UUID ", "corrected": " U U I D "},
    { "target": "Validated", "corrected": "Validated "},
    { "target": "vCPU", "corrected": " ブイ CPU "},
    { "target": "Version", "corrected": "バージョン"},    
    { "target": "WaitCondition", "corrected": "ウエイトコンディション"},
    { "target": "WaitTime", "corrected": " Wait Time "},
    { "target": "WaitOn", "corrected": " Wait On "},
    { "target": " WCU ", "corrected": " W C U "},
    { "target": "(WCU)", "corrected": "( W C U "},
    { "target": "WorkSpaces", "corrected": "ワークスペーシーズ"},
    { "target": "XGBoost", "corrected": " X G Boost "},
    { "target": "xlarge", "corrected": " x large "},
    { "target": ".yml", "corrected": "ヤムル "},
    { "target": "ZipFile", "corrected": "ジップファイル"},
    { "target": " CIDR ", "corrected": "シーアイディーアール"},
    { "target": "（EIP）", "corrected": "イーアイピー"},
    { "target": "（IGW）", "corrected": "アイジーダブリュー"},
    { "target": "(UTM)", "corrected": " U T M "},
    
    { "target": "1つ", "corrected": "ひとつ"},
    { "target": "2つ", "corrected": "ふたつ"},
    { "target": "3つ", "corrected": "みっつ"},
    { "target": "4つ", "corrected": "よっつ"},
    { "target": "5つ", "corrected": "いつつ"},
    { "target": "6つ", "corrected": "むっつ"},
    { "target": "7つ", "corrected": "ななつ"},
    { "target": "8つ", "corrected": "やっつ"},
    { "target": "9つ", "corrected": "ここのつ"},
    { "target": "１つ", "corrected": "ひとつ"},
    { "target": "２つ", "corrected": "ふたつ"},
    { "target": "３つ", "corrected": "みっつ"},
    { "target": "４つ", "corrected": "よっつ"},
    { "target": "５つ", "corrected": "いつつ"},
    { "target": "６つ", "corrected": "むっつ"},
    { "target": "７つ", "corrected": "ななつ"},
    { "target": "８つ", "corrected": "やっつ"},
    { "target": "９つ", "corrected": "ここのつ"},
    { "target": "1 つ", "corrected": "ひとつ"},
    { "target": "2 つ", "corrected": "ふたつ"},
    { "target": "3 つ", "corrected": "みっつ"},
    { "target": "4 つ", "corrected": "よっつ"},
    { "target": "5 つ", "corrected": "いつつ"},
    { "target": "6 つ", "corrected": "むっつ"},
    { "target": "7 つ", "corrected": "ななつ"},
    { "target": "8 つ", "corrected": "やっつ"},
    { "target": "9 つ", "corrected": "ここのつ"},
    { "target": "１ つ", "corrected": "ひとつ"},
    { "target": "２ つ", "corrected": "ふたつ"},
    { "target": "３ つ", "corrected": "みっつ"},
    { "target": "４ つ", "corrected": "よっつ"},
    { "target": "５ つ", "corrected": "いつつ"},
    { "target": "６ つ", "corrected": "むっつ"},
    { "target": "７ つ", "corrected": "ななつ"},
    { "target": "８ つ", "corrected": "やっつ"},
    { "target": "９ つ", "corrected": "ここのつ"},

    { "target": "。1 日", "corrected": "。いちにち"},
    { "target": "。1日", "corrected": "。いちにち"},    
    { "target": "毎日1 日", "corrected": "毎日 いちにち"},
    { "target": "毎日1日", "corrected": "毎日 いちにち"},    
    { "target": "、1日", "corrected": "、いちにち"},    
    { "target": "、1 日", "corrected": "、いちにち"},    
    
    { "target": "アイラビリティーゾーン", "corrected": "アベイラビリティーゾーン"},
    { "target": "空の", "corrected": "からの"},
    { "target": "が空", "corrected": "が、から"},
    { "target": "は行を読", "corrected": "は、行を読"},
    { "target": "根本原因", "corrected": "こんぽんげんいん"},
    { "target": "証跡", "corrected": "しょうせき"},
    { "target": "成果物", "corrected": "せいかぶつ"},
    { "target": "< ", "corrected": "  "}


]
